### ISSUE TITLE
Add support for decimals without 0 prefix (.1 vs 0.1)

### ISSUE THREAD

**Issue by EricProper** [MathosProject/Mathos-Parser#12]
Currently the evaluation of expressions containing decimal constants without a 0 prefix (such as ".1+.1") is throwing.

This occurs because Lex(".1+.1") returns [".", "1", "+", ".", "1"] instead of the expected result of [".1", "+", ".1"] (like when processing Lex("0.1+0.1")). The string list is then passed as a parameter to BasicArithmeticalExpression, where it fails to convert "." to a decimal.

**Comment by EricProper** [comment]
@napen123 @artemlos Will there be a NuGet package release in the near future? Currently still making use of MathosParser 1.0.10.1 by Artem Los from back in 2015 and would like to upgrade.

**Comment by napen123** [comment]
I think having at least a pre-release would be nice. Unfortunately, I don't have access to the NuGet package. @artemlos ping

**Comment by artemlos** [comment]
@napen123 @EricProper Sure! Anything specific we should include in the release notes?

**Comment by EricProper** [comment]
@artemlos @napen123 As some of the changes did impact public class definitions and method signatures, there are a few changes that a consumer of a package will want to know about. I have included a few:
 
**Enhancements**
- Dropped support of decimal in favor of double. **(warrants major version change)**
- CultureInfo is now able to be initialized through the MathParser constructor.
- Added "ln", "acos", "asin", "atan", "ceil" as predefined local functions.
- Minor performance improvements.
- Added MathToken.

**Bug Fixes**
- Fixed error when omitting a leading zero before a decimal point.

**Comment by napen123** [comment]
That seems like a decent list. (MathToken has since been removed, though)
