### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by napen123** [MathosProject/Mathos-Parser#14]
As discussed in #12, it might be time to start thinking about putting together a new release of the parser (at least a pre-release).

Here's a list of changes that have been made since the last version (thanks @EricProper):

- .Net Standard version added.
- Dropped support of decimal in favor of double.
- OperatorList has been removed (OperatorAction is now Operators).
- Can now initialize CultureInfo through the constructor.
- Added ln, acos, asin, atan, and ceil to the list of predefined functions.
- Can now omit the leading zero before decimal points.
- Minor performance improvements.
- Updates to XML-comments.
- Other small changes and improvements.

**Comment by napen123** [comment]
I guess Visual Studio (I'm using 2017) has the option to generate a NuGet package for the project. The option's in the Package tab in the main project's property page. I haven't used it yet, but it seems neat.

**Comment by artemlos** [comment]
@napen123 I will try to get this release out during the weekend. Sorry for not responding earlier.

**Comment by napen123** [comment]
Sounds good! 👍

**Comment by artemlos** [comment]
The page is now published, so I will close this issue: https://www.nuget.org/packages/MathosParser/.
