### ISSUE TITLE
Meaningless judgment

### ISSUE THREAD

**Issue by peach5460** [MathosProject/Mathos-Parser#6]
In MathParser/MathParser.cs Line 339

if (i != 0 && (char.IsDigit(expr[i - 1]) || char.IsDigit(expr[i - 1]) || expr[i - 1] == ')'))

I don't know why "(char.IsDigit(expr[i - 1])" write twice.
I think it's a slip of the pen.

**Comment by artemlos** [comment]
I might have missed it when I wrote the first version of the parser (which was several years ago). Thank you for pointing that out! 

I think that me and @napen123 will rewrite the entire parsing module using a parser generator, eg: http://goldparser.org/.
